FROM maven:3.6.1-jdk-8-slim
ADD target/task-management-services-0.0.1-SNAPSHOT.jar task-management-services-0.0.1-SNAPSHOT.jar

EXPOSE 8080 8080
CMD java -jar task-management-services-0.0.1-SNAPSHOT.jar




